# Generated by Django 2.1 on 2018-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180917_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='position',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_1',
            field=models.CharField(blank=True, default='/static/images/projects/', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_2',
            field=models.CharField(blank=True, default='/static/images/projects/', max_length=500, null=True),
        ),
    ]
